### ISSUE TITLE
Changing the structure of the database on the fly causes: ERROR (feature_not_supported): cached plan must not change result type

### ISSUE THREAD

**Issue by janjiss** [elixir-ecto/postgrex#212]
Okay, so this might qualify as a bug or might not, but we have a shared database between two apps. The structure does not actually change for us, but I was not able to reproduce the bug with barebones app without changing the structure of the table, hence the example changes the type of the column.

When we change the structure of the table outside of phoenix, db connections in the pool throw an error of:  ERROR (feature_not_supported): cached plan must not change result type.

New connections are not effected

### Steps to reproduce:

mix phoenix.new hello
cd hello
mix
mix phoenix.gen.json Hello hello hello:string```

Add the resource to your api scope in web/router.ex:

    resources "/hello", HelloController, except: [:new, :edit]

mix ecto.migrate
mix ecto.schema.dump

go to localhost:4000/hello

take following code from priv/repo/structure.sql that was generated by mix ecto.schema.dump:
```SQL
CREATE TABLE hello (
    id integer NOT NULL,
    hello character varying(255),
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```
and change it to:
```SQL
CREATE TABLE hello (
    id integer NOT NULL,
    hello integer,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```
Execute the query in your favourite PG client.

Refresh localhost:4000/hello and you will get: 

ERROR (feature_not_supported): cached plan must not change result type

NOTE: You might need to hit refresh several times for the query to be executed in one of the old connections or limit your pool size to 1. 

If you kill Elixir.Hello.Repo in observer or restart the app, it fixes the problem. 
The connection is not restarted after we receive this error. 

Similar issue in ActiveRecord: https://github.com/rails/rails/issues/1892

### Environment

* Elixir version (elixir -v): Elixir 1.3.1
* Phoenix version (mix deps): 
 connection 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (connection) 3145f741
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext) 80c1dd42
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch) a6fb992c
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal) 79a769d4
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* db_connection 1.0.0-rc.3 (Hex package) (mix)
  locked at 1.0.0-rc.3 (db_connection) d9ceb670
  ok
* phoenix_pubsub 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_pubsub) c31af4be
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy) a324a8df
  ok
* plug 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (plug) 8927e402
  ok
* phoenix_html 2.6.0 (Hex package) (mix)
  locked at 2.6.0 (phoenix_html) b9f7e091
  ok
* phoenix 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix) 1bdeb99c
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* postgrex 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (postgrex) 139755c1
  ok
* ecto 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ecto) b02331c1
  ok
* phoenix_ecto 3.0.0 (Hex package) (mix)
  locked at 3.0.0 (phoenix_ecto) b947aaf0
  ok
* Operating system: All

**Comment by fishcakez** [comment]
I think this is a bug in Ecto, and not Postgrex. Before I investigate this could you quickly try adding the repo option `prepare: :unnamed` and report back if the error still occurs.

**Comment by fishcakez** [comment]
There are 3 caches in Ecto/Postgrex:

1) Per (Postgrex) connection query cache for prepared queries
2) Per (Postgrex) database type cache for caching type information
3) Per (Ecto) Repo query cache for caching query generation to a prepared query

After some testing I have been able to invalidated all of these caches by changing a table while Ecto/Postgrex is running. Caches from 1) and 3) can be refreshed by restarting the Ecto Repo. I am unsure of the best way to proceed for 2). @josevalim?

**Comment by janjiss** [comment]
@fishcakez Looks like it solved the problem. Now I need to test ```prepare: :unnamed``` with the production app. Will let you know

**Comment by fishcakez** [comment]
@janjiss `prepare: :unnamed` disables the cache in 1). However the cache from 3) will be invalid and you may get hidden bugs.

**Comment by janjiss** [comment]
@fishcakez Can confirm that this fixes the issue only half way trough.

**Comment by fishcakez** [comment]
@janjiss we can track it here as we will need to make changes here before handling it in Ecto.

**Comment by fishcakez** [comment]
If we detect a feature not supported on query cache revalidation and wipe the prepared queries and types for all connections on that host's types tables. How do we inform Ecto to remove the cache queries and not to allow old queries to be inserted? Potentially we could solve this by removing entries from the cache on `ArgumentError` but that means every query needs to fail to be replaced.

**Comment by fishcakez** [comment]
I think we can only handle this by adding an option to disable the ecto prepared query cache and only cache the SQL statement (as in Ecto 1.*) because the only way to guarantee the cache does not become invalid is not to cache.

**Comment by josevalim** [comment]
Wouldn't the worst case scenario solution, which is to expire queries one
by one as we get errors, be better than not providing caching at all?



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
The query struct stores the type information, this means we can always get cases where the old type information is used to encode/decode a query that is executed on a connection that needs to prepare it. If it needs to prepare it then we won't detect the types are no longer valid because we won't fail in the backend's query cache revalidation procedure.

We could change the current method so that we check the types in the query struct match the types from the database when preparing a query on a connection that hadn't previously prepared the query. This can be done by switching to the 2 roundtrip prepare/describe and then execute cycle instead of the single roundtrip combined prepare/execute request for new prepared queries on a connection. If the describe response oids do not match the query struct we would error without executing. Therefore we would error on all queries where the Ecto cache isn't valid.

However if we have `prepare: :unnamed` we always do the single roundtrip combined prepare/execute because we never cache prepared queries at the connection level. This means we would need to do 2 roundtrip prepare/describe cycles for every query to detect invalid types in the query struct.

That approach is preferable to not caching in Ecto because we can still encode outside the connection, and don't need to describe, only check for matching `oid`s. Whereas not caching in Ecto would mean encoding and describing while holding on to the connection.

I think some people may know that they won't alter the database and should be able to pass an option to always take the single roundtrip. We could do this with `describe: :strict | :naive`, defaulting to `:strict`, which will check the query struct oids when preparing on a connection, and `:naive` does not.

If we just implement that option we would have different behaviour for strict describe inside a transaction. If we get a cache revalidation error from postgres because the query was prepared on the connection before the `ALTER TABLE` we will be in a failed transaction - unless rolled back. Whereas if the query is not prepared we will not have a protocol level error and so not fail the transaction, but return an error. I think this is ok but I can't rely on the fact on someone not getting tripped up by this.

If the Ecto cache gets updated to a new query struct and we send it to a connection that has prepared the same query with old types but has not yet detected it, we can detect this with `describe: :strict` by storing the oids for each query in the postgrex connection cache. Unfortunately we can't tell if this is an old struct on a connection with new types or a new struct on a connection with old types. If postgres allows us to prepare a query with same name/statement as an existing prepared query we can just reprepare/describe as if the query was not in the cache. However if it does not I think we will need to close all the queries and return the type mismatch error.

For naive describe we may or may not get an error we can detect if there is a type change. But it is off by default so someone would have to know what they are doing to use it and it would fail the transaction above.

If we detect an `ALTER TABLE` should we re-bootstrap for that host/database? It is possible there is a new oid. However I think it is unlikely and is probably complex. I think we should wait until someone hits this before considering it.

If we detect an `ALTER TABLE` should we close all prepared queries on that connection or just that query? I think we can close all because other queries have likely failed. Since we might be inside a failed transaction we will have to use the protocol level close to close queries one by one - but can do it in a single round trip with very little code.

There are some Ecto points that we don't need to handle yet, but I am going to put them here while I remember them.

If we detect an `ALTER TABLE` should we reset that Ecto cache entry or the full cache? And how should we inform Ecto? I think we want to reset the full cache to SQL statements so that we fail as few times as possible. Note that we may encounter 1 to `pool_size` full resets for a single `ALTER TABLE` with the full reset, whereas we would fail once per cache query with a single reset. We can leave these 2 questions until we have handled things in postgrex.

Should we add an option to disable the Ecto prepared query cache and only cache SQL statements? This would potentially allow `ALTER TABLE` without any errors. Of course it is still possible for an `ALTER TABLE` to happen between the prepare and execute so is not full proof. Again we can leave this for now.

**Comment by fishcakez** [comment]
I have started working on this.

Postgresql will error when preparing a query with the same name and statement twice but to handle cache changes we want to allow it. Should we also allow preparing a query with same and different statement?

**Comment by fishcakez** [comment]
Now tracking in ecto PR https://github.com/elixir-ecto/ecto/issues/1604

**Comment by dylan-chong** [comment]
@janjiss Was this issue resolved for you?
