### ISSUE TITLE
Raising errors causes queries not to be logged

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/postgrex#218]
We have a limitation today in that, if preparing or executing the query fails, the query is no logged. This makes it really hard to debug errors, specially if the error is related to parameter encoding/decoding as said here: https://groups.google.com/forum/#!topic/elixir-ecto/m8TdUtGgsX0

I would like to fix this and I can think of two options:

1. Fix Postgrex so it avoids raising as much as possible and instead if returns `{:error, Exception.t}`. This will improve known situations but still make it impossible for unknowns.

2. Fix DBConnection to also invoke the logger in case of errors.

I am more inclined to do 2 but I would like @fishcakez feedback before moving on.

**Comment by fishcakez** [comment]
I don't think DBConnection will allow 1) because if encode succeeds then we may do a check out, we don't want to checkout when not going to use the connection, so we have to go for 2). I think if any DBConnection or DBConnection.Query callbacks raise there isn't a log either. This means parsing, describing and prepare/execute/close/begin/commit/rollback too.

**Comment by fishcakez** [comment]
2) Is in DBConnection master but no new release yet
