### ISSUE TITLE
Read/stream large object?

### ISSUE THREAD

**Issue by drozzy** [elixir-ecto/postgrex#322]
Hi, guys.

Is there an example of how to read a large object? E.g. something like this in C:
https://www.postgresql.org/docs/current/static/lo-examplesect.html

I'm looking for a way to stream it from the server.

I see some discussion about OIDs on the main page, but not too sure if that is the same thing.

**Comment by fishcakez** [comment]
You can use the following SQL: https://www.postgresql.org/docs/9.6/static/lo-funcs.html.

`COPY` queries are also supported to read and write but I don't think that it can be combined with the previous approach and it would require putting a whole row into memory at a time when reading because thats how postgres sends data over the wire.

**Comment by josevalim** [comment]
I will close this as @fishcakez provided an answer. If it is not enough, a PR is welcome! Thanks.
