### ISSUE TITLE
Database username and password are logged on crash

### ISSUE THREAD

**Issue by freshtonic** [elixir-ecto/postgrex#340]
I'm seeing sensitive credentials (database username and password) logged when Postgrex crashes.

If someone can kindly point me in the right direction I'd be happy to fix. I think that removing the sensitive credential could be achieved by implementing the optional GenServer callback `format_status(Opt, [PDict, State]) -> Status` which is called upon process termination.

From a brief look at the `postgrex` code, it's unclear to me whether this callback should be part of `postgrex` itself or perhaps even the `db_connection` module.

Example logging of user name and password:

```
(postgrex) lib/postgrex/protocol.ex:512: Postgrex.Protocol.do_handshake(%Postgrex.Protocol{buffer: nil, connection_id: nil, connection_key: nil, null: nil, parameters: %{}, peer: {{172, 1, 1, 99}, 5432}, postgres: :idle, queries: nil, sock: {:gen_tcp, #Port<0.10837>}, timeout: 15000, transactions: :naive, types: nil}, %{opts: [types: Ecto.Adapters.Postgres.TypeModule, name: Qanda.Repo.Pool, otp_app: :qanda, repo: Qanda.Repo, timeout: 15000, pool_timeout: 5000, adapter: Ecto.Adapters.Postgres, ssl: \"false\", username: \"foo\", password: \"bar\", database: \"baz\", hostname: \"my_database_host\", port: 5432, pool: DBConnection.Poolboy],  <snip>
```

**Comment by freshtonic** [comment]
Similar issue here: https://github.com/elixir-lang/elixir/issues/6529

**Comment by fishcakez** [comment]
The output in the snippet is part of a stacktrace and not the process's state. Therefore `format_status` would not change the information. AFAIK there is not anything we can do to stop logs including function arguments in a stacktrace. A similar issue could occur with `CaseClause` or `TryClauseError` when nothing matches and it would be included in the exception itself.

Also `DBConnection` has supported the `format_status` call since its vert first commit so we avoid logging the sensitive keyword `options` lists. Postgrex doesn't implement `format_status` but never stores the sensitive data in its own state so passwords shouldn't be leak that way.

**Comment by fishcakez** [comment]
The only thing I can thing of is to try sending a PR to OTP to remove stacktrace (and exception???) information when `Process.flag(:sensitive, true)` has been called. No idea how feasible this is, or if would except it.

**Comment by freshtonic** [comment]
@fishcakez thanks for the prompt response!

In hindsight, it's clear that a stack trace would not be affected. That should have been obvious to me.

I'll do some investigation into whether an OTP PR is feasible. In the meantime, I have a workaround.

**Comment by AndrewDryga** [comment]
@freshtonic you can write your own logger and erase sensitive data there.
