### ISSUE TITLE
Is there a timeline for 1.0?

### ISSUE THREAD

**Issue by robconery** [elixir-ecto/postgrex#376]
Hi Postgrex friends! I've been working on Moebius lately and find myself in the position of thinking about the next major version (4.0). I have some ideas I want to chase down, but last time I did this (version 2.0) I ran into a problem with Timex being replaced by Elixir's date time stuff and Postgrex following suit. Long story here but I had to rev to 3.0 to deal with the date changes (and a few other things) and it wasn't fun.

Anyway: do you have a timeline for 1.0? I know that the this project is closely tied with Ecto and the two sort of develop together. The problem is that I need to think about Ecto's development and how it could change things in the core of Moebius (via the driver).

I've tossed around [the idea of moving to epgsql](https://github.com/robconery/moebius/issues/47) but I like @fishcakez work with the db connection pool bits so I'd rather not. In an ideal world the driver would be it's own project that is independent of a given ORM, but c'est la vie.

I've looked all over the repo and I don't see 1.0 mentioned other than a milestone with a single issue. I *did* see an rc-1 mentioned on Hex but it's been superceded by 0.13. It would really help me if I could be sure of the API.

**Comment by josevalim** [comment]
Hi @robconery 👋!

Regarding the datetime migration, v0.13.x still supports both Postgrex and Elixir calendar types. But v0.14+ will only support the Elixir ones, so if you already migrated to those, you are ahead of us. :+1:

There is no specific deadline for v1.0. We are working right now on DBConnection v2.0, which we want to be simpler (less code, less deps) and faster, and then we should be well on the path towards v1.0. But there is no timeline.

In any case, we do our best to avoid breaking APIs, because there are many people using Postgrex directly, but as we are still before v1.0, they may still happen from time to time.

I should also mention that we are looking for people to help maintain the adapters since, as you said, the work is mostly done by the Ecto team, which then means that the development is mostly coupled to Ecto. So if you know of anybody that is interested in helping triage, review and fix bugs, please point them our way. :)

**Comment by josevalim** [comment]
No problem!

Just to clarify, we are very open to not coupling Postgrex goals with Ecto. However, since members of the Ecto team are the only ones who maintain this project, it is really hard for that not to happen. So while we do all the work to make sure Postgrex is good for Ecto, we definitely wouldn't oppose others doing the work that suits other specific use cases too. We just can't tackle both.

Btw, [epgsql seems to have a pool too](https://github.com/epgsql/pgapp), so at least the pool concerns seem to be tackled and that should make your life much easier.
