### ISSUE TITLE
SSL not available

### ISSUE THREAD

**Issue by Secasp** [elixir-ecto/postgrex#387]
Hi, I'm trying to execute a migration with ecto, but whex it runs, the next erro message appear whent it tries to connect with de database:

```Postgrex.Protocol (#PID<0.40nect: ** (Postgrex.Error) ssl not available```

I've tried upgrading and recompiling all the libraries, incluiding the postgrex, I removed the SSL parameter located in the app configuration. It is something that I`m missing?
 
I'm using Elixir 1.6.5 version and its running on Docker from the official Elixir image.

Thanks in advance.

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help, where a wider community will be able to help you. It is much more likely that you will find someone who ran into the same issue as you in the past.

As a starting point, start `iex` and run `:ssl.start`, if it doesn't return `:ok`, there where you should start looking.

**Comment by alinpopa** [comment]
@Secasp had the same issue recently, and discovered that has nothing to do with :ssl not being loaded/available, but more with the fact that my Postgres instance wasn't ssl enabled, and that message itself is a bit misleading, telling me that I'm trying to connect through ssl to a server that is not ssl enabled. Check to see if the same problem is for you.

**Comment by Nezteb** [comment]
@Secasp @alinpopa Oddly enough, I'm running into this issue four years later using:

Elixir: `1.14.1-otp-25`
Erlang: `25.1.1`
Postgres: `postgis/postgis:13-3.1`

<img width="979" alt="Screenshot 2023-02-22 at 3 25 43 PM" src="https://user-images.githubusercontent.com/3588798/220787901-11a03215-e0ee-4446-b523-b69be0b19ad3.png">

The redacted part is just an app-specific environment variable; `MIX_ENV` is set to `dev`. As far as I know SSL shouldn't be used; I don't have any special config options set anywhere, neither in the mix project nor Postgres itself.

Things I've tried:
- Running `:ssl.start` in an `iex` session returns `:ok` as @josevalim suggested it should.
- Adding an explicit `ssl: false` config to my repo, but that doesn't work.
- Adding `:ssl` to the Mix project's `extra_applications` list.

This issue is the most relevant result when Googling "(Postgrex.Error) ssl not available", which is why I'm commenting here. I'll also post on ElixirForum though and link that thread here for transparency. 😄
