### ISSUE TITLE
Incorrect range support

### ISSUE THREAD

**Issue by karlseguin** [elixir-ecto/postgrex#397]
According to https://www.postgresql.org/docs/10.0/static/functions-range.html#RANGE-OPERATORS-TABLE, `range @> scalar` is valid. We can confirm this with:

```
psql -c "create table test as select int4range(10, 20) as range";
SELECT 1

psql -c "select * from test where range @> 15"
  range  
---------
 [10,20)
(1 row)
```

However, trying to do the same with Postgrex yields an error:
```
Postgrex.query!(pid, "select * from test where range @> $1", [15])
** (ArgumentError) Postgrex expected %Postgrex.Range{}, got 15. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
```

More generally, are there any plans to lessen the coupling to postgres types? I've run into three distinct problems with this approach.

The first, as seen here, are bugs. Removing these checks would remove the chance for inconsistency between the library and the server.

The second is having to restart an app on DB change

The third is worse logging. When these happen in Postgresql, you get more context (the actual SQL that executed it). When they happen in Postgrex you generally get less meaningful errors.

**Comment by michalmuskala** [comment]
This is not a limitation of postgrex, but rather of postgres' prepared statements.

You can replicate the problem if you use prepared statements directly in psql:
```sql
> create table test as select int4range(10, 20) as range;
-- SELECT 1
> PREPARE foo AS select * from test where range @> $1;
-- PREPARE
> EXECUTE foo(1);
-- ERROR:  parameter $1 of type integer cannot be coerced to the expected type int4range
-- HINT:  You will need to rewrite or cast the expression.
```

This is because prepared statements are always monomorphic - each parameter can only have one type.

This can be fixed by manually adding type casts to help postgres select correct types:

```sql
> PREPARE bar AS select * from test where range @> $1::integer;
-- PREPARE
> EXECUTE bar(1);
-- range
-- -------
-- (0 rows)
```

**Comment by josevalim** [comment]
Hi @karlseguin!

There is one very important thing to keep in mind: the types given in a query are different from when those values are passed as parameters. That's because, when we give a parameterized query to Postgres, it infers the types and then it asks for those specific types.

That said, we can't simply pass an integer to Postgres, because Postgres is asking for a range. We would need to cast it instead. So to me, "lessen the coupling from postgres types" is very hard, because this is imposed by Postgres itself.

> The second is having to restart an app on DB change

Can you expand on this one?

**Comment by josevalim** [comment]
@michalmuskala should we at least wrap errors coming from exception into an exception struct that also includes the query and things like parameter positions? I think this would help fixing those bugs.

**Comment by josevalim** [comment]
Opening for discussion, although I agree with @michalmuskala on the assessment of the main issue.

**Comment by michalmuskala** [comment]
Yes, we're probably able to provide a better error, but IMHO that's the extent of the improvements we could do here. We can't make it work.

**Comment by karlseguin** [comment]
Geez..I'm off today. I think my 'reload app' comment was fixed a year ago with:
https://github.com/elixir-ecto/postgrex/pull/317

Sorry.
