### ISSUE TITLE
decode > db or, decoding takes longer than IO

### ISSUE THREAD

**Issue by fenollp** [elixir-ecto/postgrex#437]
```
QUERY OK source="tournaments" db=7382.0ms decode=10204.0ms queue=0.2ms
```
```
"postgrex": {:hex, :postgrex, "0.13.5", "3d931aba29363e1443da167a4b12f06dcd171103c424de15e5f3fc2ba3e6d9c5"
```
This was fetching 50 items with each 162 fields via 10 left outter joins on pretty beefy hardware.

How can I help you guys diagnose this?

(Yes this is a lot of joins but I can't help that). Thanks!

**Comment by josevalim** [comment]
@fenollp we would need a way to reproduce it but we may not have a lot of time to dig deep into this. It seems your query is coming from Ecto, so the root cause may be in there too. One of the things you can try is profiling the query using `mix profile.*`. Probably cprof and eprof at the beginning just to have an idea where the time is spent. If there are custom types, those may be the culprits too.

Also note that Ecto 3.0 has improvements on this area, so if you are not using latest, it may be worth doing so.

If you can pinpoint  the issue to something more actionable in postgrex or ecto, then please let us know! Thanks!
