### ISSUE TITLE
Need way to sanitize string input

### ISSUE THREAD

**Issue by AdamLeMmon01** [elixir-ecto/postgrex#568]
When I try to insert the following value into a text/varchar field in postgres via this library, the driver lets it go right through and the db throws an error.

Example strings:
"string with 'single quote'"
"string with \x00 char"

I need a way to either automatically or manually sanitize the input.

This is not for a custom type, this is for the binary/string type in elixir.

What I would like to be able to do:
sanitized_value = Postgrex.String.sanitize(value)

I currently have to manually sanitize these separately. This seems like something the driver should be able to handle.

**Comment by josevalim** [comment]
Can you please provide an example of the code that you are using and the error message that you get? Postgrex works by using parameterized queries. In this case, you don't have to escape strings, because they are all sent separately from the query. You should not inject them into the query. Thank you.

**Comment by AdamLeMmon01** [comment]
Code example:
```
{:ok, pid} = Postgrex.start_link(database: "postgres")
Postgrex.query!(pid, "SELECT * FROM table1 WHERE id = $1", ["string with a \x00 in it"])
```
The error I get: 
`** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0x00
    (postgrex 0.15.10) lib/postgrex.ex:301: Postgrex.query!/4`

I want to be able to sanitize the input string so I can just strip out invalid characters. Clearly, Postgrex is already doing the validation. Can I tap into that to strip out invalid characters? I don't want to have to roll my own and hope it matches up with the set of Postgrex validations (and then update it whenever Postgrex changes).

**Comment by AdamLeMmon01** [comment]
Table schema:
```
CREATE TABLE IF NOT EXISTS public.table1
(
	id text
)
```

**Comment by josevalim** [comment]
I see. The validation is happening on the database side and if you pass something that PostgreSQL considers to be invalid encoding, then it is going to raise. The "consider" part is important because the null byte is valid UTF-8, but PostgreSQL is avoiding it.

If you want to handle only the null byte, then you could for example replace it: `String.replace(string, "\x00", "")`. However, you may also want to replace it by the unicode question-mark diamond character, which is exactly used to handle bad unicode sequences.

If you want to handle all invalid Unicode sequences, then you can use `String.chunk(string, :valid)`. I don't think Postgrex should provide a convenience for this because how you want to handle it is app specific (I would, for example, just consider the data to be invalid).
