### ISSUE TITLE
Postgrex.QueryError type `citext` can not be handled by the types module Postgrex.DefaultTypes

### ISSUE THREAD

**Issue by adampash** [elixir-ecto/postgrex#592]
I've been running into this issue sporadically in my codebase. I'm using the `citext` extension, installed on the `public` schema, and probably one time out of every 20 or so runs of my Phoenix app, I'll get this error when querying a field with `citext` type. 

```
 ** (exit) an exception was raised:
     ** (Postgrex.QueryError) type `citext` can not be handled by the types module Postgrex.DefaultTypes
         (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
         (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
         (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
         (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
         (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
         (dataloader 1.0.10) lib/dataloader/ecto.ex:695: Dataloader.Source.Dataloader.Ecto.run_batch/2
         (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
         (dataloader 1.0.10) lib/dataloader/ecto.ex:635: Dataloader.Source.Dataloader.Ecto.run_batches/1
         (dataloader 1.0.10) lib/dataloader/ecto.ex:400: Dataloader.Source.Dataloader.Ecto.run/1
         (dataloader 1.0.10) lib/dataloader.ex:148: anonymous fn/1 in Dataloader.run/1
         (elixir 1.12.3) lib/enum.ex:1586: anonymous fn/3 in Enum.map/2
         (stdlib 3.16.1) maps.erl:410: :maps.fold_1/3
         (elixir 1.12.3) lib/enum.ex:2397: Enum.map/2
         (dataloader 1.0.10) lib/dataloader.ex:168: Dataloader.run/1
         (absinthe 1.6.6) lib/absinthe/middleware/dataloader.ex:10: Absinthe.Middleware.Dataloader.before_resolution/1
         (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
         (absinthe 1.6.6) lib/absinthe/phase/document/execution/resolution.ex:49: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
```

The error will persist for that run of the server; if I restart the server, it works fine. (It reproduces locally and deployed, with about the same consistency — one out of every 20 or so runs.)

I've seen [this issue](https://github.com/elixir-ecto/postgrex/issues/303), but that doesn't look like the same problem I'm having. Like I said, _most_ of the time, it runs without issue. 

Any ideas what might be happening here? Happy to provide more information.

**Comment by josevalim** [comment]
What is your pool size? And what is the Erlang/OTP version? Unfortunately nothing immediately comes to mind, besides a lower-level bug. So I would make sure to be running on the most recent patch version of OTP and play with the pool size to see if the issue is related to the pool size. If it still persists, then I would try to isolate it in a reproducible case so we can take a look.

**Comment by adampash** [comment]
Thanks for the response!

> What is your pool size? And what is the Erlang/OTP version? 

Pool size is 10. Erlang/OTP 24. Will see if I get a repo/test case to reproduce.

**Comment by adampash** [comment]
@josevalim I haven't yet been able to set up a reproducible test case, but I was able to do some debugging on the codebase where I'm seeing the issue. When the error does show up, the `Postgrex.TypeInfo` struct for the `citext` type looks like (note the `public` namespace on `input`, `output`, `receive`, and `send`):

```elixir
%Postgrex.TypeInfo{
  array_elem: 0,
  base_type: 0,
  comp_elems: [],
  input: "public.citextin",
  oid: 1030709,
  output: "public.citextout",
  receive: "public.citextrecv",
  send: "public.citextsend",
  type: "citext"
}
```

When it's working normally/without errors, the type info looks like:

```elixir
%Postgrex.TypeInfo{
  array_elem: 0,
  base_type: 0,
  comp_elems: [],
  input: "citextin",
  oid: 1030709,
  output: "citextout",
  receive: "citextrecv",
  send: "citextsend",
  type: "citext"
}
```

If it's at all relevant, I'm using a non-default schema namespace (that is, the schema is not the `public` postgres schema) in the app where I'm seeing this behavior.

**Comment by josevalim** [comment]
Hrm. I think it is documented that we require extensions to be installed on all schemas. Could that be the root cause? But I thought that the type information is shared across all connections, so that wouldn’t explain you getting different query results unless you have different repos?

**Comment by adampash** [comment]
Ahhh okay maybe that's at the root of it? I have two different Ecto repos set up in this project for the same database — they use different credentials and have different levels of access to tables in the database. Could that cause this?

**Comment by josevalim** [comment]
The separate repos should not be a problem. My point is that 100% of the citext queries might fail in one of those repos. You just need to find out which one. :)

**Comment by adampash** [comment]
Thanks so much for the help, @josevalim. I'm going to close this while I see if I can narrow things down; if I do isolate a problem that's more than just my code, I'll update.

**Comment by guidomb** [comment]
Hi @josevalim @adampash  I know this is an old closed issue but I've been experiencing the exact same problema. With a very low probability when we create a new application instance or deploy a new version to existing applications, we get the same error but very rarely. In our case we are using Neon as our Postgres serverless database and using their pooled connections.

Restarting the server fixes the issue. This error always ocurred after a deploy but the last time it happened when I created a new application instance (using a setup script that provisions cloud infra, fly machines and runs seeds agains the newly created neon database).

```
** (Postgrex.QueryError) type `citext` can not be handled by the types module Postgrex.DefaultTypes
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.12.5) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
    (studio_phx 0.1.0) lib/mix/tasks/create_worker_user.ex:11: Mix.Tasks.App.CreateWorkerUser.run/1
    priv/repo/seeds.exs:14: (file)
    (elixir 1.18.3) lib/code.ex:1525: Code.require_file/2
    (mix 1.18.3) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
    (mix 1.18.3) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix 1.18.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.3) lib/mix/cli.ex:107: Mix.CLI.run_task/2
    /opt/homebrew/bin/mix:2: (file)
```

In our case the line causing the failure was 

```
user = Accounts.get_user_by_email("email_worker@cedalio.com")
```

the functions i the one generated by phoenix

```
  def get_user_by_email(email) when is_binary(email) do
    Repo.get_by(User, email: email)
  end
```

same for the user schema

```
  typed_schema "users" do
    field :email, :string, null: false
    field :auth_provider_user_id, :string
    field :role, :string, null: false
    field :banned, :boolean, null: false

    timestamps(type: :utc_datetime)
  end
```

We are running `CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;` in our base migration.

Any clue what the issue could be? @adampash where you able to figure out what your problem was?

**Comment by guidomb** [comment]
To add more context our application has also another schema called `archived`, I don't know if that could be an issue but the code that 's being executed that causes the error is not using the archived schema, just the public schema. In our case the archived schema is only use when a user wants to archive an object, all we do is delete it from the table in the public schema and insert in the table in the archived schema

**Comment by greg-rychlewski** [comment]
Hey @guidomb ,

We had a similar report before that was solved by setting the search path when connecting. Could you take a look at these two issues and let us know if that helps with your problem as well?

https://github.com/elixir-ecto/postgrex/issues/619
https://github.com/elixir-ecto/postgrex/pull/729

**Comment by guidomb** [comment]
@greg-rychlewski thanks for the response! I took a look at those issue but I'm not 100% sure we are facing the exact same problem but it might be related. In our case we are using [Neon](https://neon.tech) as our Postgres provider and we are using their [pooled connections](https://neon.tech/docs/connect/connection-pooling) which uses PgBouncer under-the-hood. I'm sure that the extension is installed in the public schema. I validated this by running the following query:

```sql
SELECT 
  e.extname AS extension_name,
  n.nspname AS schema_name,
  e.extversion AS version
FROM pg_extension e
JOIN pg_namespace n ON e.extnamespace = n.oid;
```

and getting the following result

| extension\_name |schema\_name |version |
| --- | --- | --- |
| plpgsql |pg\_catalog |1.0 |
| citext |public |1.6 |
| uuid\-ossp |public |1.1 |
| pg\_trgm |public |1.6 |
| unaccent |public |1.1 |
| pg\_uuidv7 |public |1.6 |

So is there anything I should explicitly do when configuring our Repo? I don't fully understand what should I do regarding setting the search path? This [issue in PgBouncer](https://github.com/pgbouncer/pgbouncer/issues/1313) seems to indicate that changing the `SEARCH_PATH` when using PgBouncer may result in problems when the connection is reused?

We do have this function

```
def safe_execute(sql, _reverse_sql \\ "") when is_binary(sql) do
    prefix = Ecto.Migration.prefix() || "public"
    execute("SET search_path TO #{prefix}")
    execute(sql)
end
```

That we use in our migrations because we use the `public` schema and also a schema called `archived`. Then when we deploy a new version our migration script runs both

```
mix ecto.migrate && mix ecto.migrate --prefix archived
```

Therefore we keep both schemas in sync. Could that be the issue? Meaning that because we are using PgBouncer some times the connection remains configured to use the archived schema in the search path and then the extension could not be found? If that's the case what's the proper way of handling this?

Thanks

> Hey [@guidomb](https://github.com/guidomb) ,
> 
> We had a similar report before that was solved by setting the search path when connecting. Could you take a look at these two issues and let us know if that helps with your problem as well?
> 
> [#619](https://github.com/elixir-ecto/postgrex/issues/619) [#729](https://github.com/elixir-ecto/postgrex/pull/729)

**Comment by guidomb** [comment]
Well seems that the issue might be that our migrations sometimes are being run using the pooled connections and that's not recommended. Because `SET` is executed at the session level there might be a path where a connection is wrongly configured. Apart from not using pooled connection to run our migrations is there anything else that should be done when configuring Ecto?

**Comment by josevalim** [comment]
Good catch on the search path stuff. That sounds like the culprit indeed.

Postgres docs also suggest using prepare: :unnamed in your repo config if using PGBouncer or similar. Other than that, you are good to go.

Btw, I think there is a way to pass the default prefix (schema) when running a migration in Ecto.

**Comment by greg-rychlewski** [comment]
Yeah I would leave out the function that changes the search path during migrations. If you set the prefix option during migrations ecto should take care of qualifying all your migrations for you. That way you don’t need search path changed. But let us know if you are seeing something different

**Comment by guidomb** [comment]
@josevalim @greg-rychlewski It's been a while since we introduced the `safe_execute` function in our codebase to be used in migrations that needed raw SQL but the main reason of having it was that, at the time, we found out that just setting `--prefix` argument when running `mix ecto.migrate` or adding `prefix` in the release task:

```elixir
Ecto.Migrator.with_repo(
          repo,
          &Ecto.Migrator.run(&1, :up, all: true, prefix: Archive.db_prefix())
        )
```

didn't work for raw SQL. It did work when executing DDL operations via Ecto schema. We considered having a separate Repo to accessed the `archived` schema but we couldn't find a way of configuring that repo to use the same migrations folders as the regular repo.

**Comment by greg-rychlewski** [comment]
For raw sql then I think you can still use the prefix but in a different way than you’re doing now. You don’t have to set the search path you just have to prefix identifiers in the right place. Like “create prefix.table” instead of “create table”. Changing the  search path lets you remove the qualifier but you can always run the same commands with qualified names

**Comment by greg-rychlewski** [comment]
I think Postgres also has a version of SET that only applies to the current transaction. SET LOCAL or something like that. If you are ok with using ddl transactions that might be another option. But I would personally recommend qualified names because I think the CONCURRENTLY commands can’t use ddl transactions

**Comment by guidomb** [comment]
@greg-rychlewski thanks for the suggestion. We decided not to go with full qualified name at the moment in order to avoid failures because somebody forgot to interpolate the schema name or write the migration twice. This happened to use several times. The SET search_path approach was less error prone (minus the problem with PgBouncer). For the time being not using pooled connections seems to avoid all the issues.
